<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

<title>ONLINE HOTEL ROOM BOOKING SYSTEM	</title>


  
<link rel="stylesheet" type="text/css" href="style.css">
</head>
<body>
<div  style="font-size:65px; margin-left:500px; margin-top:10px; color: ORANGE; font-family : FORTE; text-shadow : 5px 5px 5px white">HOTEL<br> ORANGE<br> TREE<br> </div>


<style>
h3 {position: absolute; left :170px; top: -15px; border-style :solid; border-width:medium; border-radius:25px; border-width:10px; border-color : white;}
</style>
<body>
<h3><img src="FRONT-OF-BUILDING.PNG"></h3>
</body>



<body topmargin = "50" align="CENTER" bgcolor="GRAY">


<div id="infobar" style="margin-top:0px;">
<ul>
	<li><a href="home.php">HOME</a></li>
	<li><a href="ca.php">BOOK</a></li>
	<li><a href="contact.php">CONTACT</a></li>
	<li><a href="admin.php">ADMIN</a></li>	
</ul>
</div>



<div id="div1">
<style>

h8 {position: absolute; left :230px; top : 390px; }


</style>

<body>

<h1><center>pics</center></h1>
<h8><img src="10.jpg"></h8>

</body>
</div>





<div id="div2">
<?php echo "<b>FACILITIES</b>";
	echo " <br><br><br>
	        color T.V. in all rooms<br>
		Data points at workstations and WI-FI<br>
		Tea/Coffee maker<br>
		Mini-bar<br>
		Room Service<br>
		Laundry<br>
		Direct dial telephones<br>
		Air conditioning<br>
		Iron board on request<br>
		Laptop compatible safes<br>
		Hairdryer<br>
		Shaver point in bathroom with a shaving mirror<br> "?>
</div>


<div id="div3">
<?php echo "<b>ABOUT US</b>";
	echo"
<br><br><p>We at M/S HOTEL SAI PRASAD PVT LTD. take immense pleasure in introducing to you The Hotel Orange Tree, a 3 star business hotel. We abide by the rightful status of calling it the best business hotel in the vicinity owing to its proximity to the city, yet being the budget hotel of your choice. Located 0.5 km from Nashik Railway Station, 15 km from Satpur, 12 km from Ambad Industrial Area and 8 km from Panchvati, and central bus station  it provides a central base from which to explore the city.</p> <p>  As befits the industrial hub of the nation, we ensure the latest facilities and technology to our guests. Hospitality being our motto, the hotel is impeccably suited for residential conferences, training programs, staff assemblage and dealer meetings. Get connected with our polished hospitality and contemporary comfort. Unwind after a hard day's work at your very own home away from home as we ensure you a refurbishing experience.</p>"; ?>
      
</div>


<div id="div4">
<?php echo "<b>SERVICES</b>"; 

	echo "<br><br>Doctor On Call
<br> 	Travel Assistance
<br> 	Business Place
<br> 	Car Rental
<br> 	24 hrs Fax, STD, ISD
<br> 	Internet & Email
<br> 	Laundry service / dry cleaning
<br> 	Room Service
<br> 	Bar
<br> 	Multicusine Restaurants
<br> 	All credit cards accepted
<br> 	Safe Deposit Lockers"?>
</div>



<div id="div5">
<?php echo "<b>RESTAURANTS</b>"; ?>
<style>

h4 {position: absolute; left :185px; bottom : -680px; }

</style>

<body>
<h4><img src="REST.jpg"></h4>
</body>
</div>



</body>
</html>